@startuml
participant  "HMACSHA512" as hmac
participant "BIP39" as bip

hmac -> bip : call generate(int word_count)
bip --> bip : generate the mnemonic sentence
hmac -> bip : call get_entropy()
bip --> hmac : return the entropy
@enduml
